version: '3'
services:
  memgraph:
    image: "memgraph"
    ports:
      - "7687:7687"
  corporate_struct:
    build: .
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - memgraph